<?php

/**
 * BaseOwnerObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $owner_id
 * @property int $object_id
 * @property Object $Object
 * @property Owner $Owner
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * 
 * @method int         getOwnerId()   Returns the current record's "owner_id" value
 * @method int         getObjectId()  Returns the current record's "object_id" value
 * @method Object      getObject()    Returns the current record's "Object" value
 * @method Owner       getOwner()     Returns the current record's "Owner" value
 * @method sfGuardUser getCreator()   Returns the current record's "Creator" value
 * @method sfGuardUser getEditor()    Returns the current record's "Editor" value
 * @method OwnerObject setOwnerId()   Sets the current record's "owner_id" value
 * @method OwnerObject setObjectId()  Sets the current record's "object_id" value
 * @method OwnerObject setObject()    Sets the current record's "Object" value
 * @method OwnerObject setOwner()     Sets the current record's "Owner" value
 * @method OwnerObject setCreator()   Sets the current record's "Creator" value
 * @method OwnerObject setEditor()    Sets the current record's "Editor" value
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOwnerObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('owner_object');
        $this->hasColumn('owner_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('object_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Object', array(
             'local' => 'object_id',
             'foreign' => 'id'));

        $this->hasOne('Owner', array(
             'local' => 'owner_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}