<?php

/**
 * BaseOwner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $firstname
 * @property text $surname
 * @property text $street
 * @property text $postcode
 * @property text $city
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * @property Doctrine_Collection $OwnerObject
 * 
 * @method text                getFirstname()   Returns the current record's "firstname" value
 * @method text                getSurname()     Returns the current record's "surname" value
 * @method text                getStreet()      Returns the current record's "street" value
 * @method text                getPostcode()    Returns the current record's "postcode" value
 * @method text                getCity()        Returns the current record's "city" value
 * @method sfGuardUser         getCreator()     Returns the current record's "Creator" value
 * @method sfGuardUser         getEditor()      Returns the current record's "Editor" value
 * @method Doctrine_Collection getOwnerObject() Returns the current record's "OwnerObject" collection
 * @method Owner               setFirstname()   Sets the current record's "firstname" value
 * @method Owner               setSurname()     Sets the current record's "surname" value
 * @method Owner               setStreet()      Sets the current record's "street" value
 * @method Owner               setPostcode()    Sets the current record's "postcode" value
 * @method Owner               setCity()        Sets the current record's "city" value
 * @method Owner               setCreator()     Sets the current record's "Creator" value
 * @method Owner               setEditor()      Sets the current record's "Editor" value
 * @method Owner               setOwnerObject() Sets the current record's "OwnerObject" collection
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOwner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('owner');
        $this->hasColumn('firstname', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('surname', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('street', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('postcode', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('city', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('OwnerObject', array(
             'local' => 'id',
             'foreign' => 'owner_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}