<?php

/**
 * BaseUnitInfrastructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $objectunit_id
 * @property int $infrastructure_id
 * @property Infrastructure $Infrastructure
 * @property Objectunit $Objectunit
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * 
 * @method int                getObjectunitId()      Returns the current record's "objectunit_id" value
 * @method int                getInfrastructureId()  Returns the current record's "infrastructure_id" value
 * @method Infrastructure     getInfrastructure()    Returns the current record's "Infrastructure" value
 * @method Objectunit         getObjectunit()        Returns the current record's "Objectunit" value
 * @method sfGuardUser        getCreator()           Returns the current record's "Creator" value
 * @method sfGuardUser        getEditor()            Returns the current record's "Editor" value
 * @method UnitInfrastructure setObjectunitId()      Sets the current record's "objectunit_id" value
 * @method UnitInfrastructure setInfrastructureId()  Sets the current record's "infrastructure_id" value
 * @method UnitInfrastructure setInfrastructure()    Sets the current record's "Infrastructure" value
 * @method UnitInfrastructure setObjectunit()        Sets the current record's "Objectunit" value
 * @method UnitInfrastructure setCreator()           Sets the current record's "Creator" value
 * @method UnitInfrastructure setEditor()            Sets the current record's "Editor" value
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnitInfrastructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unit_infrastructure');
        $this->hasColumn('objectunit_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('infrastructure_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Infrastructure', array(
             'local' => 'infrastructure_id',
             'foreign' => 'id'));

        $this->hasOne('Objectunit', array(
             'local' => 'objectunit_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}