<?php

/**
 * BaseObjecttype
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $objecttype
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * @property Doctrine_Collection $Object
 * 
 * @method string              getObjecttype() Returns the current record's "objecttype" value
 * @method sfGuardUser         getCreator()    Returns the current record's "Creator" value
 * @method sfGuardUser         getEditor()     Returns the current record's "Editor" value
 * @method Doctrine_Collection getObject()     Returns the current record's "Object" collection
 * @method Objecttype          setObjecttype() Sets the current record's "objecttype" value
 * @method Objecttype          setCreator()    Sets the current record's "Creator" value
 * @method Objecttype          setEditor()     Sets the current record's "Editor" value
 * @method Objecttype          setObject()     Sets the current record's "Object" collection
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjecttype extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('objecttype');
        $this->hasColumn('objecttype', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('Object', array(
             'local' => 'id',
             'foreign' => 'objecttype_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}