<?php

/**
 * BaseObjectunit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property int $object_id
 * @property int $rooms
 * @property float $rentdeposit
 * @property Doctrine_Collection $Infrastructures
 * @property Object $Object
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * 
 * @method int                 getObjectId()        Returns the current record's "object_id" value
 * @method int                 getRooms()           Returns the current record's "rooms" value
 * @method float               getRentdeposit()     Returns the current record's "rentdeposit" value
 * @method Doctrine_Collection getInfrastructures() Returns the current record's "Infrastructures" collection
 * @method Object              getObject()          Returns the current record's "Object" value
 * @method sfGuardUser         getCreator()         Returns the current record's "Creator" value
 * @method sfGuardUser         getEditor()          Returns the current record's "Editor" value
 * @method Objectunit          setObjectId()        Sets the current record's "object_id" value
 * @method Objectunit          setRooms()           Sets the current record's "rooms" value
 * @method Objectunit          setRentdeposit()     Sets the current record's "rentdeposit" value
 * @method Objectunit          setInfrastructures() Sets the current record's "Infrastructures" collection
 * @method Objectunit          setObject()          Sets the current record's "Object" value
 * @method Objectunit          setCreator()         Sets the current record's "Creator" value
 * @method Objectunit          setEditor()          Sets the current record's "Editor" value
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjectunit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('objectunit');
        $this->hasColumn('object_id', 'int', 10, array(
             'type' => 'int',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('rooms', 'int', 6, array(
             'type' => 'int',
             'length' => 6,
             ));
        $this->hasColumn('rentdeposit', 'float', 6, array(
             'type' => 'float',
             'length' => 6,
             'scale' => '2',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnitInfrastructure as Infrastructures', array(
             'local' => 'id',
             'foreign' => 'objectunit_id'));

        $this->hasOne('Object', array(
             'local' => 'object_id',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}