<?php

/**
 * BaseInfrastructure
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $short
 * @property text $description
 * @property sfGuardUser $Creator
 * @property sfGuardUser $Editor
 * @property Doctrine_Collection $UnitInfrastructure
 * 
 * @method string              getShort()              Returns the current record's "short" value
 * @method text                getDescription()        Returns the current record's "description" value
 * @method sfGuardUser         getCreator()            Returns the current record's "Creator" value
 * @method sfGuardUser         getEditor()             Returns the current record's "Editor" value
 * @method Doctrine_Collection getUnitInfrastructure() Returns the current record's "UnitInfrastructure" collection
 * @method Infrastructure      setShort()              Sets the current record's "short" value
 * @method Infrastructure      setDescription()        Sets the current record's "description" value
 * @method Infrastructure      setCreator()            Sets the current record's "Creator" value
 * @method Infrastructure      setEditor()             Sets the current record's "Editor" value
 * @method Infrastructure      setUnitInfrastructure() Sets the current record's "UnitInfrastructure" collection
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseInfrastructure extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('infrastructure');
        $this->hasColumn('short', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('description', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Creator', array(
             'local' => 'created_by',
             'foreign' => 'id'));

        $this->hasOne('sfGuardUser as Editor', array(
             'local' => 'updated_by',
             'foreign' => 'id'));

        $this->hasMany('UnitInfrastructure', array(
             'local' => 'id',
             'foreign' => 'infrastructure_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $versionable0 = new Doctrine_Template_Versionable(array(
             'versionColumn' => 'version',
             'className' => '%CLASS%Version',
             'auditLog' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
        $this->actAs($versionable0);
    }
}