<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/16 20:31:34

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rentman',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
