<?php

/**
 * InfrastructureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InfrastructureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object InfrastructureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Infrastructure');
    }
}