<?php

/**
 * Object
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Object extends BaseObject {

    public function getAddress() {
        return $this->getStreet() . ", " . $this->getPostcode() . " " . $this->getCity();
    }

    public function getUnitCount() {
        return 0;
    }

    public function getFreeUnitCount() {
        return 0;
    }

    public function getOwners() {
        $ownerObjects = Doctrine_Core::getTable("OwnerObject")->findAllByObjectId($this->getId());
        $owners = array();
        foreach ($ownerObjects as $oo) {
            $owners[] = $oo->getOwner();
        }
        return $owners;
    }

}
