<?php

/**
 * ObjectunitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjectunitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjectunitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objectunit');
    }
}