<?php

/**
 * Object
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Object extends BaseObject {

    public function __toString() {
    	return $this->getStreet() . ", " . $this->getCity();
    }
	
    public function getAddress() {
        return $this->getStreet() . ", " . $this->getPostcode() . " " . $this->getCity();
    }

    public function getUnitCount() {
        return 0;
    }

    public function getFreeUnitCount() {
        return 0;
    }

    public function getOwners() {
        $ownerObjects = Doctrine_Core::getTable("OwnerObject")->findByObjectId($this->getId());
        $owners = array();
        foreach ($ownerObjects as $oo) {
            $owners[] = $oo->getOwner();
        }
        return $owners;
    }

	public function getOwnersList() {
		$owners = $this->getOwners();
		$list = "";
		foreach ($owners as $owner) {
			$list .= $owner . "<br>";
		}
	}
    
    public function getInfrastructures() {
        return array();
    }
}
