<?php

/**
 * ObjecttypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjecttypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjecttypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objecttype');
    }
	
	public function retrieveByObjecttype() {
		return Doctrine_Core::getTable("Objecttype")->createQuery("o")->orderBy("o.objecttype")->execute();
	}
	
}