<?php

/**
 * Owner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    rentman
 * @subpackage model
 * @author     Udo Müller <info@cs-ol.de>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Owner extends BaseOwner
{
}
