<?php

/**
 * OwnerObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OwnerObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OwnerObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OwnerObject');
    }
}