<?php

/**
 * UnitInfrastructureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitInfrastructureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitInfrastructureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitInfrastructure');
    }
}