<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->changeColumn('objecttype', 'objecttype', 'string', '255', array(
             'notnull' => '1',
             ));
        $this->changeColumn('objecttype_version', 'objecttype', 'string', '255', array(
             'notnull' => '1',
             ));
    }

    public function down()
    {

    }
}