<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/17 13:06:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rentman',
  'username' => 'root',
  'password' => 'amd2000xp',
  'name' => 'doctrine',
)),);
