<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/16 21:23:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=rentman',
  'username' => 'root',
  'password' => 'amd2000xp',
  'name' => 'doctrine',
)),);
